sales_dbt:
  outputs:
    dev:
      dbname: datajourneydatapipeline
      host: dpg-crhgqjo8fa8c7392d930-a.oregon-postgres.render.com
      pass: JaGdO5UMlunE33MeShud3kJJxB1gvzT6
      port: 5432
      schema: public
      threads: 1
      type: postgres
      user: dellapostgre
  target: dev